name: JavaScript Code Quality

on:
  push:
    branches: [ Main ]
  pull_request:
    branches: [ Main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install ESLint
        run: npm install eslint

      - name: Run ESLint
        run: npx eslint **/*.js